### ISSUE TITLE
A question about the discrete optimization course material

### ISSUE THREAD

**Issue by hxd1011** [balta2ar/discrete-optimization-001#1]
Hi, there, my name is Haitao and I am a big fan of this course and spent countless hours on the assignments.

It is nice to see your code on github

Unfortunately Coursera removed all the materials from there website. Is that possible that you have some downloaded materials? such as video and slides? Could you share with me?

Thank you very much.

**Comment by balta2ar** [comment]
@hxd1011 Hello, Haitao! Sure, here you go: https://yadi.sk/d/Wm-NCBEEtCKAN.

I only have materials for the very first run of this course. If this site doesn't work for you, I can upload somewhere else or create a torrent/btsync ID, whatever works for you. Please ping me back if you manage to download this, I'll remove it as it occupies free space on my account.

**Comment by hxd1011** [comment]
@balta2ar God, you are my star!!. I got super upset when Coursera removed this course and spent many hours to get them back. Thanks a million to give me this resource. I love this course a lot and wanted to get another phd from him :). Again thanks, I am downloading it right now and will ping you when I finish. You made my day

**Comment by hxd1011** [comment]
Just let you know, I am still downloading it will notify you when I finish. Thanks again.

**Comment by hxd1011** [comment]
@balta2ar Download finished! Thank you very much for this priceless sharing !!

**Comment by hxd1011** [comment]
@balta2ar The content was great, however, there are many missing video lectures. For example in 05_Linear_Integer_programming. There are 11 lectures, captions and slides are good, but there are 7 video lectures. 

There are some problem with the upload or you do not have all of them?

Thank you!

![image](https://cloud.githubusercontent.com/assets/13385855/16744449/32e31382-477f-11e6-9b78-fa71dde2ad88.png)

**Comment by balta2ar** [comment]
@hxd1011 It looks is though I reached my quota for disk space on that service when I had uploaded these files. I've cleaned up the space and now I can see all files in week 5 - Linear Integer programming. Could you check whether you can see them too now?

**Comment by hxd1011** [comment]
Yes I can. Thank you. In fact, in additional to chapter 5, there are random missing files in many places. i will do a diff, and download the missing ones. will keep you posted on the progress.

**Comment by hxd1011** [comment]
@balta2ar I finished the download. It is 3.71G and 224 files. Could you quickly check it with me? Thank you very much. 

It is late in Moscow, have a good night. And if you do not mind, I will try to reach you in your gmail account later for some academic discussions. Also here is my linkedin profile https://www.linkedin.com/in/haitao-du-32a28220 feel free to contact for any issues if you think I can help.

**Comment by balta2ar** [comment]
Yes, number of files and size sounds right:

``` bash
$ find optimization-001 -type f | wc -l
224
$ du -sh *                             
3.7G    optimization-001
```

Sure, feel free to drop me a line! I've sent you a request on LinkedIn. I'm glad I could help!

**Comment by hxd1011** [comment]
Thanks, keep in touch.
